FROM cgr.dev/garrett.crosby/python:3.13-dev

USER root

ENV UV_COMPILE_BYTECODE=1
ENV UV_NO_CACHE=1

WORKDIR /app

RUN apk add --no-cache cmake curl uv

COPY README.md /app/
COPY pyproject.toml /app/
RUN uv sync --no-install-project --no-dev
COPY src /app/src

EXPOSE 8000

ENTRYPOINT ["uv", "run", "python", "-m", "api_module.main"]